#!/usr/bin/env python

import pandas as pd
from argparse import ArgumentParser
import pyranges as pr
from pyranges import PyRanges
import numpy as np

from methplotlib.differential.differential import main

def pyranges_from_csv(inputfile):
    colnames = ["Chromosome", "Start", "End", "calls", "methylated"]
    return PyRanges(pd.read_csv(inputfile, sep="\t", names=colnames, header=0, usecols=[0, 1, 2, 4, 5]))


def get_args():
    parser = ArgumentParser(
        description="Check for modification differences using fisher exact test.")
    parser.add_argument(
        "-b", "--bed", help="Bed file to aggregate modifications on.", required=True)
    parser.add_argument("-A", "--Agroup", nargs='+', help="Frequencies of group A.")
    parser.add_argument("-B", "--Bgroup", nargs='+', help="Frequencies of group B.")
    parser.add_argument("-o", "--out", help="File to write results to. Default: stdout.", default="-")
    return parser.parse_args()


if __name__ == '__main__':

    args = get_args()

    a_range = pr.concat([pyranges_from_csv(f) for f in args.Agroup])
    b_range = pr.concat([pyranges_from_csv(f) for f in args.Bgroup])
    bed = pr.read_bed(args.bed).merge()

    gr = main(a_range, b_range, bed)

    f = args.out

    if f == "-":
        import sys
        gr.to_csv(sys.stdout, sep="\t")# index=False)
    else:
        from pathlib import Path

        p = Path(f)
        Path.mkdir(p.parent, exist_ok=True, parents=True)

        gr.to_csv(str(p), sep="\t")



